spring:
  main:
    banner-mode: off
  application:
    name: datadrift

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: duaa
    password: secret
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: DataDriftHikariPool

datadrift:
  changelog:
    directory: file:./changelog/
  lock:
    max-retry-attempts: 5
    retry-delay-ms: 1000

logging:
  level:
    root: WARN
    com.datadrift: WARN
  pattern:
    console: "%msg%n"
